# Sebastien Galvagno  06/2023


from Parser.Template import Template


class cytosenseModel(Template):
    _mapping = {
        #'object_date':{ 'file' : "ROI" , 'header' :'Date', 'index' : 1 , 'fn' : "date" , 'type' : '[t]', 'comment': 'Date'},
        'img_file_name':{ 'file' : None , 'header' :None, 'index' : 0 , 'fn' : "image" , 'type' : '[t]', 'comment': 'image'},
        'img_rank':{ 'file':None, 'header':None, 'index':0, 'fn':"rank", 'type':'[f]', 'comment': 'rank'},
    }

    def __init__(self, models=[]):  # Array<Template>
        for model in models:
            self.append(model.mapping)
        super().__init__()

    # def key(self,key):
    #     super().key(key)

# head -1 'ATSO_photos_flr16_2uls_10min 2022-06-15 16h31_Pulses.csv' | sed 's/;/\n/g' | sed 's/^/"object_date":{ "file" : "Pulses" , "header" :"/g' | sed 's/$/","index":1, "fn": None, "type":"[t]", "comment":""},/g' | awk '{gsub("index\":1","index\":" NR-1,$0);print}'
class pulseOld(Template):
    #'object_date':{ 'file' : "Pulses" , 'header' :'Date', 'index' : 1 , 'fn' : "date" , 'type' : '[t]', 'comment': 'Date'},
    _mapping = {
        "object_id": {
            "file": "Pulses",
            "header": "Particle ID",
            "index": 0,
            "fn": "define_id",
            "type": "[t]",
            "comment": "",
        },
        "object_fws": {
            "file": "Pulses",
            "header": "FWS",
            "index": 1,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_sws": {
            "file": "Pulses",
            "header": "SWS",
            "index": 2,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_fl_erllow": {
            "file": "Pulses",
            "header": "FL Yellow",
            "index": 3,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_fl_orange": {
            "file": "Pulses",
            "header": "FL Orange",
            "index": 4,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_fl_red": {
            "file": "Pulses",
            "header": "FL Red",
            "index": 5,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_curvature": {
            "file": "Pulses",
            "header": "Curvature",
            "index": 6,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
    }

# head -1 tests/cytosense/pulse_fits.csv | sed 's/,/\n/g' | sed 's/^/"object_":{ "file" : "Listmode" , "header" :"/g' | sed 's/$/","index":1, "fn": None, "type":"[f]", "comment":""},/g' | awk '{gsub("index\":1","index\":" NR-1,$0);print}' -> pulse.txt 
class pulse(Template):
    '''pulse in polynomial form'''
    
    def define_id(self, id, data):
        return data._data['sample_name'] + "_" + str(id)
        # return id


    _mapping = {'object_id': {'file': 'Listmode', 'header': 'Particle ID', 'index': 0, 'fn': "define_id", 'type': '[t]', 'comment': ''}, 'object_coef_0_FWS': {'file': 'Listmode', 'header': 'FWS_coef_0', 'index': 5, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_FWS': {'file': 'Listmode', 'header': 'FWS_coef_1', 'index': 11, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_FWS': {'file': 'Listmode', 'header': 'FWS_coef_2', 'index': 17, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_FWS': {'file': 'Listmode', 'header': 'FWS_coef_3', 'index': 23, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_FWS': {'file': 'Listmode', 'header': 'FWS_coef_4', 'index': 29, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_FWS': {'file': 'Listmode', 'header': 'FWS_coef_5', 'index': 35, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_FWS': {'file': 'Listmode', 'header': 'FWS_coef_6', 'index': 41, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_FWS': {'file': 'Listmode', 'header': 'FWS_coef_7', 'index': 47, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_FWS': {'file': 'Listmode', 'header': 'FWS_coef_8', 'index': 53, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_FWS': {'file': 'Listmode', 'header': 'FWS_coef_9', 'index': 59, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_0_SWS': {'file': 'Listmode', 'header': 'SWS_coef_0', 'index': 6, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_SWS': {'file': 'Listmode', 'header': 'SWS_coef_1', 'index': 12, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_SWS': {'file': 'Listmode', 'header': 'SWS_coef_2', 'index': 18, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_SWS': {'file': 'Listmode', 'header': 'SWS_coef_3', 'index': 24, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_SWS': {'file': 'Listmode', 'header': 'SWS_coef_4', 'index': 30, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_SWS': {'file': 'Listmode', 'header': 'SWS_coef_5', 'index': 36, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_SWS': {'file': 'Listmode', 'header': 'SWS_coef_6', 'index': 42, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_SWS': {'file': 'Listmode', 'header': 'SWS_coef_7', 'index': 48, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_SWS': {'file': 'Listmode', 'header': 'SWS_coef_8', 'index': 54, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_SWS': {'file': 'Listmode', 'header': 'SWS_coef_9', 'index': 60, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_0_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_0', 'index': 4, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_1', 'index': 10, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_2', 'index': 16, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_3', 'index': 22, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_4', 'index': 28, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_5', 'index': 34, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_6', 'index': 40, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_7', 'index': 46, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_8', 'index': 52, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_FL_Yellow': {'file': 'Listmode', 'header': 'FL Yellow_coef_9', 'index': 58, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_0_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_0', 'index': 1, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_1', 'index': 8, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_2', 'index': 14, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_3', 'index': 20, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_4', 'index': 26, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_5', 'index': 32, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_6', 'index': 38, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_7', 'index': 44, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_8', 'index': 50, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_FL_Orange': {'file': 'Listmode', 'header': 'FL Orange_coef_9', 'index': 56, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_0_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_0', 'index': 3, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_1', 'index': 9, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_2', 'index': 15, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_3', 'index': 21, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_4', 'index': 27, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_5', 'index': 33, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_6', 'index': 39, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_7', 'index': 45, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_8', 'index': 51, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_FL_Red': {'file': 'Listmode', 'header': 'FL Red_coef_9', 'index': 57, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_0_curvature': {'file': 'Listmode', 'header': 'Curvature_coef_0', 'index': 2, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_1_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_1', 'index': 7, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_2_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_2', 'index': 13, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_3_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_3', 'index': 19, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_4_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_4', 'index': 25, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_5_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_5', 'index': 31, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_6_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_6', 'index': 37, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_7_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_7', 'index': 43, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_8_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_8', 'index': 49, 'fn': None, 'type': '[f]', 'comment': ''}, 'object_coef_9_Curvature': {'file': 'Listmode', 'header': 'Curvature_coef_9', 'index': 60, 'fn': None, 'type': '[f]', 'comment': ''}}

    _mapping2 = {
        "object_id":{ "file" : "Listmode" , "header" :"Particle ID","index":0, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_0"        ,"index":5, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_1"        ,"index":11, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_2"        ,"index":17, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_3"        ,"index":23, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_4"        ,"index":29, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_5"        ,"index":35, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_6"        ,"index":41, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_7"        ,"index":47, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_8"        ,"index":53, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_FWS":{ "file" : "Listmode"       , "header" :"FWS_coef_9"        ,"index":59, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_0"        ,"index":6, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_1"        ,"index":12, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_2"        ,"index":18, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_3"        ,"index":24, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_4"        ,"index":30, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_5"        ,"index":36, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_6"        ,"index":42, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_7"        ,"index":48, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_8"        ,"index":54, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_SWS":{ "file" : "Listmode"       , "header" :"SWS_coef_9"        ,"index":60, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_0"  ,"index":4, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_1"  ,"index":10, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_2"  ,"index":16, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_3"  ,"index":22, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_4"  ,"index":28, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_5"  ,"index":34, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_6"  ,"index":40, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_7"  ,"index":46, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_8"  ,"index":52, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_FL_Yellow":{ "file" : "Listmode" , "header" :"FL Yellow_coef_9"  ,"index":58, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_0"  ,"index":1, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_1"  ,"index":8, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_2"  ,"index":14, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_3"  ,"index":20, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_4"  ,"index":26, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_5"  ,"index":32, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_6"  ,"index":38, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_7"  ,"index":44, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_8"  ,"index":50, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_FL_Orange":{ "file" : "Listmode" , "header" :"FL Orange_coef_9"  ,"index":56, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_0"     ,"index":3, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_1"     ,"index":9, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_2"     ,"index":15, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_3"     ,"index":21, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_4"     ,"index":27, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_5"     ,"index":33, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_6"     ,"index":39, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_7"     ,"index":45, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_8"     ,"index":51, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_FL_Red":{ "file" : "Listmode"    , "header" :"FL Red_coef_9"     ,"index":57, "fn": None, "type":"[f]", "comment":""},

        "object_coef_0_curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_0"  ,"index":2, "fn": None, "type":"[f]", "comment":""},
        "object_coef_1_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_1"  ,"index":7, "fn": None, "type":"[f]", "comment":""},
        "object_coef_2_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_2"  ,"index":13, "fn": None, "type":"[f]", "comment":""},
        "object_coef_3_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_3"  ,"index":19, "fn": None, "type":"[f]", "comment":""},
        "object_coef_4_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_4"  ,"index":25, "fn": None, "type":"[f]", "comment":""},
        "object_coef_5_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_5"  ,"index":31, "fn": None, "type":"[f]", "comment":""},
        "object_coef_6_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_6"  ,"index":37, "fn": None, "type":"[f]", "comment":""},
        "object_coef_7_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_7"  ,"index":43, "fn": None, "type":"[f]", "comment":""},
        "object_coef_8_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_8"  ,"index":49, "fn": None, "type":"[f]", "comment":""},
        "object_coef_9_Curvature":{ "file" : "Listmode" , "header" :"Curvature_coef_9"  ,"index":55, "fn": None, "type":"[f]", "comment":""},        
    }


# head -1 'ATSO_photos_flr16_2uls_10min 2022-06-15 16h31_Listmode.csv' | sed 's/;/\n/g' | sed 's/^/"object_date":{ "file" : "Listmode" , "header" :"/g' | sed 's/$/","index":1, "fn": None, "type":"[t]", "comment":""},/g' | awk '{gsub("index\":1","index\":" NR-1,$0);print}' > listnode.txt
class UlcoListmode(Template):

    def define_id(self, id, data):
        return data._data['sample_name'] + "_" + str(id)
        # return id

    def sample_id(self, id, data):
        return data._data['sample_name']
    


    _mapping = {
        "object_id": {
            "file": "Listmode",
            "header": "Particle ID",
            "index": 0,
            "fn": "define_id",
            "type": "[t]",
            "comment": "",
        },
        "sample_id": {
            "file": "Listmode",
            "header": "Particle ID",
            "index": 0,
            "fn": "sample_id",
            "type": "[t]",
            "comment": "",
        },
        "sample_length": {
            "file": "Listmode",
            "header": "Sample Length",
            "index": 1,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_arrival_time": {
            "file": "Listmode",
            "header": "Arrival Time",
            "index": 2,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_length": {
            "file": "Listmode",
            "header": "FWS Length",
            "index": 3,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_total": {
            "file": "Listmode",
            "header": "FWS Total",
            "index": 4,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_maximum": {
            "file": "Listmode",
            "header": "FWS Maximum",
            "index": 5,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_average": {
            "file": "Listmode",
            "header": "FWS Average",
            "index": 6,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_inertia": {
            "file": "Listmode",
            "header": "FWS Inertia",
            "index": 7,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_center_of_gravity": {
            "file": "Listmode",
            "header": "FWS Center of gravity",
            "index": 8,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_fill_factor": {
            "file": "Listmode",
            "header": "FWS Fill factor",
            "index": 9,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_asymmetry": {
            "file": "Listmode",
            "header": "FWS Asymmetry",
            "index": 10,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_number_of_cells": {
            "file": "Listmode",
            "header": "FWS Number of cells",
            "index": 11,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_first": {
            "file": "Listmode",
            "header": "FWS First",
            "index": 12,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_last": {
            "file": "Listmode",
            "header": "FWS Last",
            "index": 13,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_minimum": {
            "file": "Listmode",
            "header": "FWS Minimum",
            "index": 14,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_sws_covariance": {
            "file": "Listmode",
            "header": "FWS SWS covariance",
            "index": 15,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_length": {
            "file": "Listmode",
            "header": "SWS Length",
            "index": 16,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_total": {
            "file": "Listmode",
            "header": "SWS Total",
            "index": 17,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_maximum": {
            "file": "Listmode",
            "header": "SWS Maximum",
            "index": 18,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_average": {
            "file": "Listmode",
            "header": "SWS Average",
            "index": 19,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_inertia": {
            "file": "Listmode",
            "header": "SWS Inertia",
            "index": 20,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_center_of_gravity": {
            "file": "Listmode",
            "header": "SWS Center of gravity",
            "index": 21,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_fill_factor": {
            "file": "Listmode",
            "header": "SWS Fill factor",
            "index": 22,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_asymmetry": {
            "file": "Listmode",
            "header": "SWS Asymmetry",
            "index": 23,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_number_of_cells": {
            "file": "Listmode",
            "header": "SWS Number of cells",
            "index": 24,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_first": {
            "file": "Listmode",
            "header": "SWS First",
            "index": 25,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_last": {
            "file": "Listmode",
            "header": "SWS Last",
            "index": 26,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_minimum": {
            "file": "Listmode",
            "header": "SWS Minimum",
            "index": 27,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_sws_covariance": {
            "file": "Listmode",
            "header": "SWS SWS covariance",
            "index": 28,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_length": {
            "file": "Listmode",
            "header": "FL Yellow Length",
            "index": 29,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_total": {
            "file": "Listmode",
            "header": "FL Yellow Total",
            "index": 30,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_maximum": {
            "file": "Listmode",
            "header": "FL Yellow Maximum",
            "index": 31,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_average": {
            "file": "Listmode",
            "header": "FL Yellow Average",
            "index": 32,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_inertia": {
            "file": "Listmode",
            "header": "FL Yellow Inertia",
            "index": 33,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_center_of_gravity": {
            "file": "Listmode",
            "header": "FL Yellow Center of gravity",
            "index": 34,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_fill_factor": {
            "file": "Listmode",
            "header": "FL Yellow Fill factor",
            "index": 35,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_asymmetry": {
            "file": "Listmode",
            "header": "FL Yellow Asymmetry",
            "index": 36,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_number_of_cells": {
            "file": "Listmode",
            "header": "FL Yellow Number of cells",
            "index": 37,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_first": {
            "file": "Listmode",
            "header": "FL Yellow First",
            "index": 38,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_last": {
            "file": "Listmode",
            "header": "FL Yellow Last",
            "index": 39,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_minimum": {
            "file": "Listmode",
            "header": "FL Yellow Minimum",
            "index": 40,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_sws_covariance": {
            "file": "Listmode",
            "header": "FL Yellow SWS covariance",
            "index": 41,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_length": {
            "file": "Listmode",
            "header": "FL Orange Length",
            "index": 42,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_total": {
            "file": "Listmode",
            "header": "FL Orange Total",
            "index": 43,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_maximum": {
            "file": "Listmode",
            "header": "FL Orange Maximum",
            "index": 44,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_average": {
            "file": "Listmode",
            "header": "FL Orange Average",
            "index": 45,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_inertia": {
            "file": "Listmode",
            "header": "FL Orange Inertia",
            "index": 46,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_center_of_gravity": {
            "file": "Listmode",
            "header": "FL Orange Center of gravity",
            "index": 47,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_fill_factor": {
            "file": "Listmode",
            "header": "FL Orange Fill factor",
            "index": 48,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_asymmetry": {
            "file": "Listmode",
            "header": "FL Orange Asymmetry",
            "index": 49,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_number_of_cells": {
            "file": "Listmode",
            "header": "FL Orange Number of cells",
            "index": 50,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_first": {
            "file": "Listmode",
            "header": "FL Orange First",
            "index": 51,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_last": {
            "file": "Listmode",
            "header": "FL Orange Last",
            "index": 52,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_minimum": {
            "file": "Listmode",
            "header": "FL Orange Minimum",
            "index": 53,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_sws_covariance": {
            "file": "Listmode",
            "header": "FL Orange SWS covariance",
            "index": 54,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_length": {
            "file": "Listmode",
            "header": "FL Red Length",
            "index": 55,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_total": {
            "file": "Listmode",
            "header": "FL Red Total",
            "index": 56,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_maximum": {
            "file": "Listmode",
            "header": "FL Red Maximum",
            "index": 57,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_average": {
            "file": "Listmode",
            "header": "FL Red Average",
            "index": 58,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_inertia": {
            "file": "Listmode",
            "header": "FL Red Inertia",
            "index": 59,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_center_of_gravity": {
            "file": "Listmode",
            "header": "FL Red Center of gravity",
            "index": 60,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_fill_factor": {
            "file": "Listmode",
            "header": "FL Red Fill factor",
            "index": 61,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_asymmetry": {
            "file": "Listmode",
            "header": "FL Red Asymmetry",
            "index": 62,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_number_of_cells": {
            "file": "Listmode",
            "header": "FL Red Number of cells",
            "index": 63,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_first": {
            "file": "Listmode",
            "header": "FL Red First",
            "index": 64,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_last": {
            "file": "Listmode",
            "header": "FL Red Last",
            "index": 65,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_minimum": {
            "file": "Listmode",
            "header": "FL Red Minimum",
            "index": 66,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_sws_covariance": {
            "file": "Listmode",
            "header": "FL Red SWS covariance",
            "index": 67,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        # "object_curvature_length": {
        #     "file": "Listmode",
        #     "header": "Curvature Length",
        #     "index": 68,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_total": {
        #     "file": "Listmode",
        #     "header": "Curvature Total",
        #     "index": 69,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_maximum": {
        #     "file": "Listmode",
        #     "header": "Curvature Maximum",
        #     "index": 70,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_average": {
        #     "file": "Listmode",
        #     "header": "Curvature Average",
        #     "index": 71,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_inertia": {
        #     "file": "Listmode",
        #     "header": "Curvature Inertia",
        #     "index": 72,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_center_of_gravity": {
        #     "file": "Listmode",
        #     "header": "Curvature Center of gravity",
        #     "index": 73,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_fill_factor": {
        #     "file": "Listmode",
        #     "header": "Curvature Fill factor",
        #     "index": 74,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_asymmetry": {
        #     "file": "Listmode",
        #     "header": "Curvature Asymmetry",
        #     "index": 75,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_number_of_cells": {
        #     "file": "Listmode",
        #     "header": "Curvature Number of cells",
        #     "index": 76,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_first": {
        #     "file": "Listmode",
        #     "header": "Curvature First",
        #     "index": 77,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_last": {
        #     "file": "Listmode",
        #     "header": "Curvature Last",
        #     "index": 78,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_minimum": {
        #     "file": "Listmode",
        #     "header": "Curvature Minimum",
        #     "index": 79,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
        # "object_curvature_sws_covariance": {
        #     "file": "Listmode",
        #     "header": "Curvature SWS covariance",
        #     "index": 80,
        #     "fn": None,
        #     "type": "[f]",
        #     "comment": "",
        # },
    }


class CefasListmode(Template):
    _mapping = {
        "object_id": {
            "file": "Listmode",
            "header": "﻿Particle ID",
            "index": 0,
            "fn": "define_id",
            "type": "[f]",
            "comment": "",
        },
        "sample_id": {
            "file": "Listmode",
            "header": "Particle ID",
            "index": 0,
            "fn": "sample_id",
            "type": "[t]",
            "comment": "",
        },
        "sample_length": {
            "file": "Listmode",
            "header": "Sample Length",
            "index": 1,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_arrival_time": {
            "file": "Listmode",
            "header": "Arrival Time",
            "index": 2,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_length": {
            "file": "Listmode",
            "header": "FWS Length",
            "index": 3,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_total": {
            "file": "Listmode",
            "header": "FWS Total",
            "index": 4,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_maximum": {
            "file": "Listmode",
            "header": "FWS Maximum",
            "index": 5,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_average": {
            "file": "Listmode",
            "header": "FWS Average",
            "index": 6,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_inertia": {
            "file": "Listmode",
            "header": "FWS Inertia",
            "index": 7,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_center_of_gravity": {
            "file": "Listmode",
            "header": "FWS Center of gravity",
            "index": 8,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_fill_factor": {
            "file": "Listmode",
            "header": "FWS Fill factor",
            "index": 9,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "object_fws_asymmetry": {
            "file": "Listmode",
            "header": "FWS Asymmetry",
            "index": 10,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_number_of_cells": {
            "file": "Listmode",
            "header": "FWS Number of cells",
            "index": 11,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_first": {
            "file": "Listmode",
            "header": "FWS First",
            "index": 12,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_last": {
            "file": "Listmode",
            "header": "FWS Last",
            "index": 13,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_minimum": {
            "file": "Listmode",
            "header": "FWS Minimum",
            "index": 14,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_sws_covariance": {
            "file": "Listmode",
            "header": "FWS SWS covariance",
            "index": 15,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fws_length_50": {
            "file": "Listmode",
            "header": "FWS Length(50%)",
            "index": 16,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_length": {
            "file": "Listmode",
            "header": "Sidewards Scatter Length",
            "index": 17,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_total": {
            "file": "Listmode",
            "header": "Sidewards Scatter Total",
            "index": 18,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_maximum": {
            "file": "Listmode",
            "header": "Sidewards Scatter Maximum",
            "index": 19,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_average": {
            "file": "Listmode",
            "header": "Sidewards Scatter Average",
            "index": 20,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_inertia": {
            "file": "Listmode",
            "header": "Sidewards Scatter Inertia",
            "index": 21,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_center_of_gravity": {
            "file": "Listmode",
            "header": "Sidewards Scatter Center of gravity",
            "index": 22,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_fill_factor": {
            "file": "Listmode",
            "header": "Sidewards Scatter Fill factor",
            "index": 23,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_asymmetry": {
            "file": "Listmode",
            "header": "Sidewards Scatter Asymmetry",
            "index": 24,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_number_of_cells": {
            "file": "Listmode",
            "header": "Sidewards Scatter Number of cells",
            "index": 25,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_first": {
            "file": "Listmode",
            "header": "Sidewards Scatter First",
            "index": 26,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_last": {
            "file": "Listmode",
            "header": "Sidewards Scatter Last",
            "index": 27,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_minimum": {
            "file": "Listmode",
            "header": "Sidewards Scatter Minimum",
            "index": 28,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_sws_covariance": {
            "file": "Listmode",
            "header": "Sidewards Scatter SWS covariance",
            "index": 29,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_sidewards_scatter_length_50": {
            "file": "Listmode",
            "header": "Sidewards Scatter Length(50%)",
            "index": 30,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_length": {
            "file": "Listmode",
            "header": "Fl Yellow Length",
            "index": 31,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_total": {
            "file": "Listmode",
            "header": "Fl Yellow Total",
            "index": 32,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_maximum": {
            "file": "Listmode",
            "header": "Fl Yellow Maximum",
            "index": 33,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_average": {
            "file": "Listmode",
            "header": "Fl Yellow Average",
            "index": 34,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_inertia": {
            "file": "Listmode",
            "header": "Fl Yellow Inertia",
            "index": 35,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_center_of_gravity": {
            "file": "Listmode",
            "header": "Fl Yellow Center of gravity",
            "index": 36,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_fill_factor": {
            "file": "Listmode",
            "header": "Fl Yellow Fill factor",
            "index": 37,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_asymmetry": {
            "file": "Listmode",
            "header": "Fl Yellow Asymmetry",
            "index": 38,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_number_of_cells": {
            "file": "Listmode",
            "header": "Fl Yellow Number of cells",
            "index": 39,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_first": {
            "file": "Listmode",
            "header": "Fl Yellow First",
            "index": 40,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_last": {
            "file": "Listmode",
            "header": "Fl Yellow Last",
            "index": 41,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_minimum": {
            "file": "Listmode",
            "header": "Fl Yellow Minimum",
            "index": 42,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_sws_covariance": {
            "file": "Listmode",
            "header": "Fl Yellow SWS covariance",
            "index": 43,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_yellow_length_50": {
            "file": "Listmode",
            "header": "Fl Yellow Length(50%)",
            "index": 44,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_length": {
            "file": "Listmode",
            "header": "Fl Orange Length",
            "index": 45,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_total": {
            "file": "Listmode",
            "header": "Fl Orange Total",
            "index": 46,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_maximum": {
            "file": "Listmode",
            "header": "Fl Orange Maximum",
            "index": 47,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_average": {
            "file": "Listmode",
            "header": "Fl Orange Average",
            "index": 48,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_inertia": {
            "file": "Listmode",
            "header": "Fl Orange Inertia",
            "index": 49,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_center_of_gravity": {
            "file": "Listmode",
            "header": "Fl Orange Center of gravity",
            "index": 50,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_fill_factor": {
            "file": "Listmode",
            "header": "Fl Orange Fill factor",
            "index": 51,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_asymmetry": {
            "file": "Listmode",
            "header": "Fl Orange Asymmetry",
            "index": 52,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_number_of_cells": {
            "file": "Listmode",
            "header": "Fl Orange Number of cells",
            "index": 53,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_first": {
            "file": "Listmode",
            "header": "Fl Orange First",
            "index": 54,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_last": {
            "file": "Listmode",
            "header": "Fl Orange Last",
            "index": 55,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_minimum": {
            "file": "Listmode",
            "header": "Fl Orange Minimum",
            "index": 56,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_sws_covariance": {
            "file": "Listmode",
            "header": "Fl Orange SWS covariance",
            "index": 57,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_orange_length_50": {
            "file": "Listmode",
            "header": "Fl Orange Length(50%)",
            "index": 58,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_length": {
            "file": "Listmode",
            "header": "Fl Red Length",
            "index": 59,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_total": {
            "file": "Listmode",
            "header": "Fl Red Total",
            "index": 60,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_maximum": {
            "file": "Listmode",
            "header": "Fl Red Maximum",
            "index": 61,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_average": {
            "file": "Listmode",
            "header": "Fl Red Average",
            "index": 62,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_inertia": {
            "file": "Listmode",
            "header": "Fl Red Inertia",
            "index": 63,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_center_of_gravity": {
            "file": "Listmode",
            "header": "Fl Red Center of gravity",
            "index": 64,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_fill_factor": {
            "file": "Listmode",
            "header": "Fl Red Fill factor",
            "index": 65,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_asymmetry": {
            "file": "Listmode",
            "header": "Fl Red Asymmetry",
            "index": 66,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_number_of_cells": {
            "file": "Listmode",
            "header": "Fl Red Number of cells",
            "index": 67,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_first": {
            "file": "Listmode",
            "header": "Fl Red First",
            "index": 68,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_last": {
            "file": "Listmode",
            "header": "Fl Red Last",
            "index": 69,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_minimum": {
            "file": "Listmode",
            "header": "Fl Red Minimum",
            "index": 70,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_sws_covariance": {
            "file": "Listmode",
            "header": "Fl Red SWS covariance",
            "index": 71,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "object_fl_red_length_50": {
            "file": "Listmode",
            "header": "Fl Red Length(50%)",
            "index": 72,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
    }


# sed 's/:.*//g' 'ATSO_photos_flr16_2uls_10min 2022-06-15 16h31_Info.txt' | sed 's/^/"object_date":{ "file" : "Info" , "header" :"/g' | sed 's/$/","index":1, "fn": None, "type":"[t]", "comment":""},/g' | awk '{gsub("index\":1","index\":" NR-1,$0);print}' > info.txt

class Info(Template):
    
    # def changeTimeToNumericValue(self,value):
    #     import pandas
    #     pandas.to_timedelta(value, unit='s')
    
    # Question : is channel order can change?
    _mapping = {
        "acq_trigger_level": {
            "file": "Info",
            "header": "Trigger level (mV)",
            "index": 1,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_cytousb_block_size": {
            "file": "Info",
            "header": "CytoUSB Block size",
            "index": 2,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "acq_instrument": {
            "file": "Info",
            "header": "Instrument",
            "index": 4,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "acq_beam_width": {
            "file": "Info",
            "header": "Beam width",
            "index": 5,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_core_speed": {
            "file": "Info",
            "header": "Core speed",
            "index": 6,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_user_comments": {
            "file": "Info",
            "header": "User Comments",
            "index": 7,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_measurement_date": {
            "file": "Info",
            "header": "Measurement date",
            "index": 9,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_measurement_duration": {
            "file": "Info",
            "header": "Measurement duration",
            "index": 10,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_flow_rate": {
            "file": "Info",
            "header": "Flow rate (μL/sec)",
            "index": 11,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_channel_1": {
            "file": "Info",
            "header": "Channel 1",
            "index": 13,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_2": {
            "file": "Info",
            "header": "Channel 2",
            "index": 14,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_3": {
            "file": "Info",
            "header": "Channel 3",
            "index": 15,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_4": {
            "file": "Info",
            "header": "Channel 4",
            "index": 16,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_4_pmt_level": {
            "file": "Info",
            "header": "  - sensitivity level",
            "index": 17,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_channel_5": {
            "file": "Info",
            "header": "Channel 5",
            "index": 18,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_5_pmt_level": {
            "file": "Info",
            "header": "  - sensitivity level",
            "index": 19,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_channel_6": {
            "file": "Info",
            "header": "Channel 6",
            "index": 20,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_6_pmt_level": {
            "file": "Info",
            "header": "  - sensitivity level",
            "index": 21,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_channel_7": {
            "file": "Info",
            "header": "Channel 7",
            "index": 22,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_channel_7_pmt_level": {
            "file": "Info",
            "header": "  - sensitivity level",
            "index": 23,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_total_number_of_particles": {
            "file": "Info",
            "header": "Total number of particles",
            "index": 25,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_smart_triggered_number_of_particles": {
            "file": "Info",
            "header": "Smart triggered number of particles",
            "index": 26,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_concentration": {  # We leave the units out of the name
            "file": "Info",
            "header": "Concentration (part/μL)",
            "index": 27,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_volume": {
            "file": "Info",
            "header": "Volume (μL)",
            "index": 28,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
    }


class Info_RecursiveModel(Template):
    # Question : is channel order can change?
    _mapping = {
        "acq_trigger_level": {
            "file": "Info",
            "header": "Trigger level (mV)",
            "index": 0,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_cytousb_block_size": {
            "file": "Info",
            "header": "CytoUSB Block size",
            "index": 1,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "acq_instrument": {
            "file": "Info",
            "header": "Instrument",
            "index": 3,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "acq_beam_width": {
            "file": "Info",
            "header": "Beam width",
            "index": 4,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_core_speed": {
            "file": "Info",
            "header": "Core speed",
            "index": 5,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "acq_user_comments": {
            "file": "Info",
            "header": "User Comments",
            "index": 6,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_measurement_date": {
            "file": "Info",
            "header": "Measurement date",
            "index": 8,
            "fn": None,
            "type": "[t]",
            "comment": "",
        },
        "sample_measurement_duration": {
            "file": "Info",
            "header": "Measurement duration",
            "index": 9,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_flow_rate": {
            "file": "Info",
            "header": "Flow rate (μL/sec)",
            "index": 10,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_channel_1": {
            "file": "Info",
            "header": "Channel 1",
            "index": 12,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_1_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 16,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
            }
        },
        "sample_channel_2": {
            "file": "Info",
            "header": "Channel 2",
            "index": 13,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_2_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 16,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                }, 
            }
        },       
        "sample_channel_3": {
            "file": "Info",
            "header": "Channel 3",
            "index": 14,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_3_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 16,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
            }
        },

        "sample_channel_4": {
            "file": "Info",
            "header": "Channel 4",
            "index": 15,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_4_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 16,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
}
        },
        "sample_channel_5": {
            "file": "Info",
            "header": "Channel 5",
            "index": 17,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_5_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 18,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
            }
        },

        "sample_channel_6": {
            "file": "Info",
            "header": "Channel 6",
            "index": 19,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_6_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 20,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
            }
        },

        "sample_channel_7": {
            "file": "Info",
            "header": "Channel 7",
            "index": 21,
            "fn": None,
            "type": "[t]",
            "comment": "",
            "paragraph":{
                    "sample_channel_7_pmt_level": {
                    "file": "Info",
                    "header": "  - sensitivity level",
                    "index": 22,
                    "fn": None,
                    "type": "[f]",
                    "comment": "",
                },
            }
        },
        "sample_total_number_of_particles": {
            "file": "Info",
            "header": "Total number of particles",
            "index": 24,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_smart_triggered_number_of_particles": {
            "file": "Info",
            "header": "Smart triggered number of particles",
            "index": 25,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_concentration": {  # We leave the units out of the name
            "file": "Info",
            "header": "Concentration (part/μL)",
            "index": 26,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
        "sample_volume": {
            "file": "Info",
            "header": "Volume (μL)",
            "index": 27,
            "fn": None,
            "type": "[f]",
            "comment": "",
        },
    }

