/'Sebastien Galvagno '/

@startuml

class cpics{
    cpicsPath: string
    projectPath: string

    listFile()
    getDataFromFile()
}

class fs {
    listFile()
    create_folder()
    copyFile()
}

class tsv 

cpics *.. tsv
cpics *.. fs


@enduml
